[package]
name = "bitcoin-handshake"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.13"
clap = { version = "4.5", features = ["derive"] }
hex = "0.4"
sha2 = "0.10"
tokio = { version = "1", features = ["full"] }
